
DROP TABLE IF EXISTS "beaches";
DROP SEQUENCE IF EXISTS beaches_id_seq;
CREATE SEQUENCE beaches_id_seq INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1;

CREATE TABLE "public"."beaches" (
    "id" integer DEFAULT nextval('beaches_id_seq') NOT NULL,
    "title" character varying(255) NOT NULL,
    "description" character varying(255) DEFAULT 'Nádherná unikátní pláž' NOT NULL,
    "imageUrl" character varying(255) DEFAULT '/images/beach.webp' NOT NULL,
    "text" text NOT NULL,
    "type" character varying(255) NOT NULL,
    CONSTRAINT "beaches_pkey" PRIMARY KEY ("id")
)
WITH (oids = false);

INSERT INTO "beaches" ("id", "title", "description", "imageUrl", "text", "type") VALUES
(2,	'Altinkum',	'Jemný písek a křišťálová voda',	'',	'Altınkum znamená „Zlatý písek“ – má rozsáhlou písečnou pláž s promenádou, klasifikovanou jako Blue flag - což značí ty nejkrásnější pláže Turecka. Voda je křišťálově čistá, průzračná a mělká, vhodná pro rodiny i vodní sporty. Písek je jemňoučký a je zde velice čisto. Nutno podotknout, že je velice studená po celou dobu roku. Můžete si přinést vlastní deku na Halk plaj - veřejnou pláž a nebo pokud si budete chtít pronajmout lehátka se slunečníky a vstupem na placenou pláž se sprchami a barem, budete muset zaplatit zpravidla hodně vysokou částku - 30 až 50Euro.',	'písek'),
(7,	'Ekmeksiz',	'Menší přírodní písečná pláž',	'/images/beaches/ekmeksiz.jpg',	'Ekmeksiz pláž je klidná pláž v přírodě poblíž İzmiru, je zde krásný bílý písek. Skvělá volba mimo hlavní turistické lokality, bohužel voda je zde hodně studená po celý rok.',	'písek'),
(1,	'Ilica',	'Bílý písek jako z Malediv a termální voda',	'/images/beaches/ilica.jpg',	'Pláž Ilıca u Çeşme má cca 1,5 km dlouhý pás jemného bílého písku. Voda je mělká, teplá a v některých místech termální prameny vstupují přímo do moře. Jedná se o nejteplejší pláž Izmiru. Pláž je ideální pro rodiny s dětmi i windsurfingové nadšence. Je vždy potřeba ale koukat na směr větru, pokud fouká ze severu, je lepší zvolit jinou pláž.',	'písek'),
(8,	'Akarca',	'Oblážková pláž se studenou vodou',	'/images/beaches/akarca.jpg',	'Akarca je veřejná pláž s oblázky a kamínky nedaleko Seferihisaru. Najdete zde mnoho plážových barů, které jsou velmi levné a často je možné vyjednat další slevy. V ceně obvykle bývají zahrnutá lehátka a slunečníky, případně se můžete posadit přímo v restauraci – při minimální konzumaci často získáte například stůl zdarma. Voda je zde ale velmi studená, a to kvůli mořským proudům; těžko byste v okolí hledali chladnější koupání.',	'kamínky'),
(5,	'Yoncaköy',	'Široký hnědý písek a klidné tyrkysové vody',	'/images/beaches/yoncakoy.webp',	'Yoncaköy je malá osada letních vilek, která nabízí velkou širokou soukromou pláž. Je na ní zlatavý písek a voda je mělká. Stín lze najít pod palmami. Pláž je známá především místním a nenajdete zde téměř žádné turisty. Skvělé pro rodiny.',	'písek'),
(17,	'Kuşadası – Yilanci Burnu',	'Pláž s palmami a výhledem na hrad',	'/images/beaches/yillan.jpg',	'Pláž u Yılancı Burnu – malebný poloostrov s kamenitými plážemi, které tu a tam přechází do písku - boty do vody se určitě budou hodit. Výhled na malý ostrůvek s hradem, díky kterému tato oblast získala jméno - Ptačí ostrov. Místo je snadno dostupné z centra Kuşadası.',	'kameny'),
(9,	'Cumhuriyet / Ürkmez',	'Městská klidná písečná pláž',	'/images/beaches/urkmez.jpg',	'Cumhuriyet / Ürkmez je klidná městská pláž s šedavým pískem, místy posetá drobnými oblázky, a s čistou průzračnou vodou. Pláž je velmi dlouhá a podél ní vede široký promenádní chodník lemovaný palmami. Můžete se zde pohodlně procházet kolem místních podniků, dětských hřišť, nebo se projet na kole. Na pláži se často nacházejí neplacené městské slunečníky a sprchy, které zpříjemňují pobyt návštěvníkům. Tato pláž slouží především místním, kteří zde mají své chatky, a turistický ruch není tolik patrný. Cizince zde potkáte jen zřídka a i tureckých turistů je tu málo. Na pláž se vydejte zejména tehdy, když vane vítr ze severu.',	'písek'),
(4,	'Pamucak',	'Dlouhá pláž s pískovou deltou pro kempování',	'/images/beaches/pamucak.jpg',	'Pamucak leží poblíž Efezu. 7 km dlouhá písečná pláž je tvořena říčním žlutým zlatavým pískem. Je velmi pozvolná. Klidné místo ideální pro rodinný odpočinek s výhledem na západ slunce. Potkáte tu často karavany, které zde kempují. Sledujte vždy, aby vítr nevál přímo k pláži, mohl by přinášet chaluhy.',	'písek'),
(15,	'İçmeler Milli Park',	'Mělká písečná pláž v národním parku',	'/images/beaches/icmeler.jpg',	'İçmeler se nachází v Milli Parku, tedy v národním parku. Platí se zde malé vstupné a v parku najdete různé pláže. Pláž je první a díky pozvolnému vstupu a jemnému písku bývá nejvíce obsazená. Je velice vhodná pro malé děti. Voda je teplá a čistá. Na pláž nefouká, jelikož ji stíní řecký Samos.',	'písek'),
(16,	'Güzelçamlı / Davutlar',	'Pláž s kombinací písku a menších kamínků',	'/images/beaches/davutlar.webp',	'Güzelçamlı / Davutlar je vlastně pásmo různých pláží, které jsou však stejné - písčito-kamenité. Není nutnost mít do vody boty, jelikož písku je opravdu hodně, ale mísí se s kameny. Voda má příjemnou teplotu a díky ostrovu Samos na toto pobřeží tolik nefouká, takže je voda průzračná, čistá a je zde vidět hodně ryb.',	'kamínky'),
(3,	'Gümüldür',	'Klidná pláž se zlatým pískem',	'/images/beaches/gumuldur.webp',	'Pláž Gümüldür leží jihovýchodně od İzmiru a nabízí jemný žlutozlatý písek, čistou vodu a základní vybavení za nízký poplatek (lehátka, slunečníky, toalety). Jedná se však o pláž sdílenou s místními a mohou se zde na některých místech objevovat odpadky. Pláž je ale pozvolná, vhodná pro děti. Koukejte také na vítr, tato pláž je úžasná, pokud vane severní vítr.',	'písek'),
(6,	'Akkum',	'Veřejná pláž s lehátky',	'/images/beaches/akkum.jpg',	'Akkum u Sigaciku je písečná pláž, kde naleznete městská lehátka a slunečníky zdarma, jsou ale většinou v sezóně brzo obsazená protože je pláž hodně oblíbená. Vedle pláže jsou však menší kavárny a bufety, což je ideální pokud hledáte pláž se zázemím. Voda je čistá, ale žlutý písek a hodně lidí ji většinou zakalí.',	'písek'),
(14,	'Aydinlik Beach',	'Romantická malá písečná pláž',	'/images/beaches/karasu.jpg',	'Aydınlık Beach – malá romantická písečná pláž poblíž Kuşadası/Güzelçamlı, čistá tyrkysová voda a tichá poloha.',	'písek'),
(12,	'Karasu Milli Park',	'Průzračná voda v národním parku',	'/images/beaches/karasu.jpg',	'Karasu se nachází v Milli Parku, tedy v národním parku. Platí se zde malé vstupné a v parku najdete různé pláže. Pláž není přelidněná. Pláž je tvořena většími šedými oblázky, přesto není nutné mít do vody boty. Voda je naprosto jedinečná, teplá, průzračná. Na pláž nefouká, jelikož ji stíní řecký Samos. Ve vodě je to jako v akváriu a plave zde mnoho krásných ryb, je vhodná pro šnorchlování. Není třeba s sebou brát slunečník, pláž lemuje les ze kterého často chodí ochočená divoká prasata a hledají na plážích zbytky jídla po turistech. Pláž není mělká a celkem brzy postupně přechází do velké hloubky.',	'kamínky'),
(11,	'Deliklikoy',	'Netradiční pláž pro šnorchlování',	'/images/beaches/delikli.avif',	'Deliklikoy je bílá písčito-kamenitá netradiční pláž ukrytá nedaleko Alaçatı. Název „Deliklikoy“ v překladu znamená „díravá zátoka“ – podle charakteristického skalního oblouku s otvorem, který je ikonickým symbolem tohoto místa. Lze totiž vplout dovnitř do skály, kde se nachází malá pláž, která dírou ústí ven. Ležet můžete na velkém útesu nebo je opodál pláž. Je to vhodné místo pro kempování. Na pláži se nachází velké množství toulavých psů. Voda je zde nádherně křištálově čistá, možná je studená, ale je jako akvárium. Různé korály, útesy a spousta ryb láká milovníky šnorchlování.

',	'kamínky'),
(19,	'Çark / Alacati',	'Bělostná pláž s jemným pískem',	'/images/beaches/alacati.webp',	'Nádherná pozvolná pláž, která má bílý písek a průzračně čistou vodu - která je bohužel hodně studená. Část pláže je zdarma, kam si můžete dát svoji deku a slunečník, část patří luxusním hotelům a můžete si zde na značně vysoký poplatek pronajmout lehátko a využívat zázemí baru. Při vstupu je také levnější malá restaurace, kde najdete starší wc a nápoje a občerstvení za lepší ceny. Pláž je vhodná pro nejmenší, jelikož je opravdu hodně mělká. Procházet se můžete po celé délce pláže - ikdyž je část například hotelová, v Turecku platí pravidlo 3 metry od moře patří vždy veřejnosti a nejde tam zakázat pohyb neplatícím osobám. Je zde také půjčovna vodních sportů, kde si můžete vyzkoušet různé vodní atrakce – od jízdy na nafukovacím banánu, přes vodní kruh, až po vodní skútry. O kousek dál, na jiné pláži v blízkosti, se navíc nachází i oblíbená lokalita pro kitesurfing.',	'písek'),
(13,	'Zeus jeskyně',	'Koupání v jeskyni',	'/images/beaches/zeus.webp',	'Diova jeskyně je volně a zdarma přístupná a nachází se před vstupem do Milli Parku. Voda je sice smaragdově zelená a čistá, ale velice studená. Určitě je dobré zde míst boty do vody, jelikož vstupuje se přes kluzké a velké, ostré kameny. Místní lidé věří, že koupel ve vodě jeskyně přináší zdraví, krásu a mládí. Podle řecké mytologie se Zeus ukrýval právě v této jeskyni, když utíkal před hněvem svého bratra Poseidona, boha moří, kterého rozzlobil. Poseidon prý rozpoutal obrovskou bouři a vlny, aby Zeuse zastavil. Zeus pak našel úkryt právě v této jeskyni, kde si v chladné vodě odpočinul a zchladil hněv svého bratra.',	'kameny');

DROP TABLE IF EXISTS "trips";
DROP SEQUENCE IF EXISTS trips2_id_seq;
CREATE SEQUENCE trips2_id_seq INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1;

CREATE TABLE "public"."trips" (
    "id" integer DEFAULT nextval('trips2_id_seq') NOT NULL,
    "title" character varying(255) NOT NULL,
    "description" character varying(255) DEFAULT 'Zažijte jedinečný výlet' NOT NULL,
    "imageUrl" character varying(255) DEFAULT '/images/beach.webp' NOT NULL,
    "text" text NOT NULL,
    CONSTRAINT "trips2_pkey" PRIMARY KEY ("id")
)
WITH (oids = false);

INSERT INTO "trips" ("id", "title", "description", "imageUrl", "text") VALUES
(1,	'Výlet na ostrov Chios',	'Voňavý ostrov s historií',	'/images/egitimler/chios.jpg',	'Chios je malebný řecký ostrov známý svou unikátní přírodou, mastichovými stromy a tradičními vesnicemi. Navštívíte slavné kláštery, projdete se po úzkých uličkách středověkých měst a užijete si pohled na tyrkysové moře. Ideální pro ty, kteří chtějí zažít autentické Řecko mimo hlavní turistické trasy.'),
(2,	'Objevování antického Efesu',	'Starověké ruiny plné příběhů',	'/images/egitimler/efes.jpg',	'Efes je jedním z nejlépe zachovalých antických měst na světě. Projdete se slavnou Celsovou knihovnou, divadlem pro 25 000 diváků i nádhernou mramorovou třídou. Výlet do Efesu je cestou zpět v čase, kde ožívá slavná římská historie.'),
(3,	'Trhy a vůně Kemeraltı',	'Barevný svět tureckého bazaru',	'/images/egitimler/kemeralti.png',	'Kemeraltı je živé tržiště v srdci Izmiru, kde zažijete pravou orientální atmosféru. Úzké uličky plné koření, čajoven, historických mešit a obchůdků vás vtáhnou do světa plného barev a vůní. Ideální pro milovníky kultury, suvenýrů a dobrého jídla.'),
(4,	'Plavba na ostrov Samos',	'Zelený ráj s plážemi snů',	'/images/egitimler/samos.jpg',	'Samos, rodný ostrov Pythagora, je ideálním místem pro jednodenní výlet z tureckého pobřeží. Čekají vás malebné vesničky, vinice, krásné pláže a přívětivá řecká pohostinnost. Nezapomenutelný den plný slunce, moře a odpočinku.'),
(5,	'Klidné Seferihisar na dosah',	'Pomalu žijící město tradic',	'/images/egitimler/seferihisar.jpeg',	'Seferihisar je první turecké město s označením Pomalé město. Najdete tu klid, čistotu, tradiční trhy, autentickou kuchyni a přátelské obyvatele. Ideální pro ty, kdo hledají odpočinek mimo rušná letoviska.');

